// widgets/svelte_widget/src/App.svelte
<script lang="ts">
  import type { WidgetSDK, WidgetProps } from "./types";

  let { sdk }: { sdk: WidgetSDK } = $props();
  let props: WidgetProps = $state(sdk.getProps());

  $effect(() => sdk.on("propsChanged", (newProps: WidgetProps) => {
    props = newProps;
  }));
</script>

<section class="svelte-widget-section">
  <h3 class="svelte-widget-title">{props.title}</h3>
  {#if props.description}
    <p class="svelte-widget-description">{props.description}</p>
  {/if}
</section>

// widgets/vue_widget/src/App.vue
<script setup lang="ts">
import { ref, onUnmounted } from "vue";
import type { WidgetSDK, WidgetProps } from "./types";

const { sdk } = defineProps<{ sdk: WidgetSDK }>();

const widgetProps = ref<WidgetProps>(sdk.getProps());

const unsubscribe = sdk.on("propsChanged", (newProps: WidgetProps) => {
  widgetProps.value = newProps;
});

onUnmounted(() => unsubscribe());
</script>

<template>
  <section class="vue-widget-section">
    <h3 class="vue-widget-title">{{ widgetProps.title }}</h3>
    <p v-if="widgetProps.description" class="vue-widget-description">{{ widgetProps.description }}</p>
  </section>
</template>
