// widgets/solid_vite/src/App.tsx
import { createSignal, onMount, onCleanup, Show } from "solid-js";
import type { WidgetSDK, WidgetProps } from "./types";

export default function App({ sdk }: { sdk: WidgetSDK }) {
  const [config, setConfig] = createSignal<WidgetProps>(sdk.getProps());

  onMount(() => {
    const cleanup = sdk.on("propsChanged", setConfig);
    onCleanup(cleanup);
  });

  return (
    <section class="solid-widget-section">
      <h3 class="solid-widget-title">{config().title}</h3>
      <Show when={config().description}>
        <p class="solid-widget-description">{config().description as string}</p>
      </Show>
    </section>
  );
}

// widgets/preact_esbuild/src/App.tsx
import { useState, useEffect } from "preact/hooks";
import type { WidgetSDK, WidgetProps } from "./types";

export function App({ sdk }: { sdk: WidgetSDK }) {
  const [config, setConfig] = useState<WidgetProps>(sdk.getProps());

  useEffect(() => sdk.on("propsChanged", setConfig), [sdk]);

  return (
    <section class="preact-widget-section">
      <h3 class="preact-widget-title">{config.title}</h3>
      {config.description && (
        <p class="preact-widget-description">{config.description}</p>
      )}
    </section>
  );
}
