// widgets/angular_esbuild_widget/src/app.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-widget',
  standalone: true,
  template: `
    <section class="angular-widget-section">
      <h3 class="angular-widget-title">{{ title }}</h3>
      @if (description) {
        <p class="angular-widget-description">{{ description }}</p>
      }
    </section>
  `,
  styles: [
    `
      .angular-widget-section {
        font-family: system-ui, -apple-system, sans-serif;
        padding: 1.5rem;
        background: linear-gradient(135deg, #dd0031 0%, #c3002f 50%, #1976d2 100%);
        border-radius: 8px;
        color: white;
      }
      .angular-widget-title {
        font-size: 1.5rem;
        font-weight: 600;
        margin: 0 0 0.5rem;
      }
      .angular-widget-description {
        font-size: 1rem;
        margin: 0;
        opacity: 0.9;
      }
    `,
  ],
})
export class AppComponent {
  @Input() title: string = 'Angular Widget';
  @Input() description: string = '';
}

// widgets/react_webpack_widget/src/App.tsx
import { useState, useEffect } from "react";
import styled from "styled-components";
import type { WidgetSDK, WidgetProps } from "./types";

const Section = styled.section`
  padding: 2rem;
  font-family: "Inter", system-ui, -apple-system, sans-serif;
  border-radius: 12px;
  background: linear-gradient(135deg, #f97316 0%, #db2777 100%);
  color: #ffffff;
  min-height: 120px;
  display: flex;
  flex-direction: column;
  justify-content: center;
`;

const Title = styled.h3`
  margin: 0;
  font-size: 1.5rem;
  font-weight: 700;
  letter-spacing: -0.025em;
`;

const Description = styled.p`
  margin: 0.75rem 0 0;
  font-size: 1rem;
  opacity: 0.85;
  line-height: 1.6;
`;

export function App({ sdk }: { sdk: WidgetSDK }) {
  const [props, setProps] = useState<WidgetProps>(sdk.getProps());

  useEffect(() => sdk.on("propsChanged", setProps), [sdk]);

  return (
    <Section>
      <Title>{props.title}</Title>
      {props.description && <Description>{props.description}</Description>}
    </Section>
  );
}
