// widgets/react_widget/src/App.tsx
import { useState, useEffect } from "react";
import type { WidgetSDK, WidgetProps } from "./types";

export function App({ sdk }: { sdk: WidgetSDK }) {
  const [props, setProps] = useState<WidgetProps>(sdk.getProps());

  useEffect(() => sdk.on("propsChanged", setProps), [sdk]);

  return (
    <section className="react-widget-section">
      <h3 className="react-widget-title">{props.title}</h3>
      {props.description && (
        <p className="react-widget-description">{props.description}</p>
      )}
    </section>
  );
}

// widgets/svelte_widget/src/App.svelte
<script lang="ts">
  import type { WidgetSDK, WidgetProps } from "./types";

  let { sdk }: { sdk: WidgetSDK } = $props();
  let props: WidgetProps = $state(sdk.getProps());

  $effect(() => sdk.on("propsChanged", (newProps: WidgetProps) => {
    props = newProps;
  }));
</script>

<section class="svelte-widget-section">
  <h3 class="svelte-widget-title">{props.title}</h3>
  {#if props.description}
    <p class="svelte-widget-description">{props.description}</p>
  {/if}
</section>
