// widgets/svelte_vite/src/App.svelte
<script lang="ts">
  import type { WidgetSDK, WidgetProps } from "./types";

  const { sdk }: { sdk: WidgetSDK } = $props();
  let widgetConfig = $state<WidgetProps>(sdk.getProps());

  $effect(() => sdk.on("propsChanged", (p: WidgetProps) => {
    widgetConfig = p;
  }));
</script>

<section class="svelte-widget-section">
  <h3 class="svelte-widget-title">{widgetConfig.title}</h3>
  {#if widgetConfig.description}
    <p class="svelte-widget-description">{widgetConfig.description}</p>
  {/if}
</section>

<style>
  .svelte-widget-section {
    font-family: sans-serif;
    padding: 1rem;
  }

  .svelte-widget-title {
    font-size: 1.25rem;
    margin: 0 0 0.5rem;
    color: #ff3e00;
  }

  .svelte-widget-description {
    margin: 0;
    color: #4a4a4a;
  }
</style>

// widgets/angular_cli/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  standalone: true,
  template: `
    <section class="angular-widget-section">
      <h3 class="angular-widget-title">{{ title }}</h3>
      @if (description) {
        <p class="angular-widget-description">{{ description }}</p>
      }
    </section>
  `,
  styles: [`
    .angular-widget-section {
      font-family: sans-serif;
      padding: 1rem;
    }
    .angular-widget-title {
      font-size: 1.25rem;
      margin: 0 0 0.5rem;
      color: #dd0031;
    }
    .angular-widget-description {
      margin: 0;
      color: #4a4a4a;
    }
  `],
})
export class AppComponent {
  title = "Angular Widget";
  description = "A widget built with Angular 18 and the Angular CLI.";
}
