// widgets/vue_vite/src/App.vue
<template>
  <section class="vue-widget-section">
    <h3 class="vue-widget-title">{{ widgetConfig.title }}</h3>
    <p v-if="widgetConfig.description" class="vue-widget-description">
      {{ widgetConfig.description }}
    </p>
  </section>
</template>

<script setup lang="ts">
import { ref, onUnmounted } from "vue";
import type { WidgetSDK, WidgetProps } from "./types";

const { sdk } = defineProps<{ sdk: WidgetSDK }>();
const widgetConfig = ref<WidgetProps>(sdk.getProps());
const cleanup = sdk.on("propsChanged", (p: WidgetProps) => {
  widgetConfig.value = p;
});

onUnmounted(cleanup);
</script>

<style scoped>
.vue-widget-section {
  font-family: sans-serif;
  padding: 1rem;
}

.vue-widget-title {
  font-size: 1.25rem;
  margin: 0 0 0.5rem;
  color: #42b883;
}

.vue-widget-description {
  margin: 0;
  color: #4a4a4a;
}
</style>

// widgets/svelte_vite/src/App.svelte
<script lang="ts">
  import type { WidgetSDK, WidgetProps } from "./types";

  const { sdk }: { sdk: WidgetSDK } = $props();
  let widgetConfig = $state<WidgetProps>(sdk.getProps());

  $effect(() => sdk.on("propsChanged", (p: WidgetProps) => {
    widgetConfig = p;
  }));
</script>

<section class="svelte-widget-section">
  <h3 class="svelte-widget-title">{widgetConfig.title}</h3>
  {#if widgetConfig.description}
    <p class="svelte-widget-description">{widgetConfig.description}</p>
  {/if}
</section>

<style>
  .svelte-widget-section {
    font-family: sans-serif;
    padding: 1rem;
  }

  .svelte-widget-title {
    font-size: 1.25rem;
    margin: 0 0 0.5rem;
    color: #ff3e00;
  }

  .svelte-widget-description {
    margin: 0;
    color: #4a4a4a;
  }
</style>
