// widgets/react_widget/src/main.tsx
import { createRoot } from "react-dom/client";
import { App } from "./App";
import type { WidgetSDK } from "./types";

export async function init(sdk: WidgetSDK) {
  await sdk.whenReady();

  const root = createRoot(sdk.shadowRoot);
  root.render(<App sdk={sdk} />);
  sdk.on("destroy", () => root.unmount());
}

// widgets/solid_vite/src/main.tsx
import { render } from "solid-js/web";
import App from "./App";
import type { WidgetSDK } from "./types";

export async function init(sdk: WidgetSDK) {
  await sdk.whenReady();
  const container = document.createElement("div");
  (sdk.shadowRoot as unknown as Element).appendChild(container);
  const dispose = render(() => <App sdk={sdk} />, container);
  sdk.on("destroy", dispose);
}
